version: '3'
services: 
  jenkins:
    build: ./jenkins
    ports: 
      - "{{ .Config.JENKINS_PORT }}:8080"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock